apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://my.api.com/api/v1"
    username: dbuser
    password: 83da45f7-ce6b-4a6d-9e3a-5b4a55e2ede0